######## DATABASE CONFIGURATION
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  profiles:
    active: dev
server:
  servlet:
    context-path: /app-poorbnb

