DROP TABLE IF EXISTS USUARIO;

CREATE TABLE USUARIO (
	
	ID_USUARIO 	    INT(10) AUTO_INCREMENT PRIMARY KEY,
	CPF_CNPJ 	    INT(14) NOT NULL,
	NOME		    VARCHAR(50) NOT NULL,
	EMAIL		    VARCHAR(255) NOT NULL,
	SENHA		    VARCHAR(255) NOT NULL,
	DT_NASC	        DATE NOT NULL,
	DT_REGISTRO	    DATE NOT NULL,
	TIPO_USUARIO	CHAR(1) NOT NULL,
	ENDERECO	    VARCHAR(255) NOT NULL,
	TELEFONE	    VARCHAR(15) NOT NULL

);

ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT check_tp_user CHECK (TIPO_USUARIO IN ('C', 'H', 'A'));
-- ALTER TABLE PUBLIC.USUARIO ADD CONSTRAINT pk_id_user PRIMARY KEY REFERENCES (ID_USUARIO);

-- CREATE SEQUENCE SQ_ID_USUARIO
-- 	START WITH     1
-- 	INCREMENT BY   1
-- 	NOCACHE
-- 	NOCYCLE;

-- ALTER TABLE POORBNB.HOTEL ADD COLUMN DESATIVADO_S_N CHAR(1);
-- ALTER TABLE HOTEL ADD CONSTRAINT CHECK (DESATIVADO_S_N IN ('S', 'N'));
--
DROP TABLE IF EXISTS HOTEL;

CREATE TABLE HOTEL (

	ID_HOTEL		    INT(10) AUTO_INCREMENT PRIMARY KEY,
	NOME_HOTEL 		    VARCHAR(55),
	ID_PROPRIETARIO 	INT(10),
	ID_QUARTO		    INT(10),
	ENDERECO		    VARCHAR(255) NOT NULL,
	TELEFONE		    VARCHAR(15) NOT NULL,
	TELEFONE_OPC		VARCHAR(15),
	DESATIVADO_S_N	    CHAR(1)
);
--
ALTER TABLE HOTEL ADD CONSTRAINT fk_id_user_hotel FOREIGN KEY (ID_PROPRIETARIO) REFERENCES USUARIO(ID_USUARIO)
	    ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE HOTEL ADD CONSTRAINT check_des_s_n CHECK (DESATIVADO_S_N IN ('S', 'N'));

-- CREATE SEQUENCE SQ_ID_HOTEL
-- 	START WITH     1
-- 	INCREMENT BY   1
-- 	NOCACHE
-- 	NOCYCLE;

DROP TABLE IF EXISTS RESERVA;

CREATE TABLE RESERVA (

	COD_RESERVA	    INT(10) NOT NULL,
	ID_USUARIO 	    INT(10),
	ID_HOTEL	    INT(10),
	ID_QUARTO	    INT(10),
	DT_ENTRADA	    DATE NOT NULL,
	DT_SAIDA	    DATE NOT NULL,
	TOTAL_RESERVA	DECIMAL(10, 2) NOT NULL
);

ALTER TABLE RESERVA ADD CONSTRAINT fk_id_hotel FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL);

ALTER TABLE RESERVA	ADD CONSTRAINT fk_id_user_reserva FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

-- CREATE INDEX idx_cod_reserva ON RESERVA (COD_RESERVA)
-- 	TABLESPACE poorbnb
-- 	STORAGE (INITIAL 20K
--       	NEXT 20k
--       	PCTINCREASE 75);

DROP TABLE IF EXISTS QUARTO;

CREATE TABLE QUARTO (
	ID_QUARTO 	INT(10) AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO	VARCHAR(255) NOT NULL,
	PRECO		DECIMAL(10, 2) NOT NULL,
	OCUPADO_S_N	CHAR(1) NOT NULL
);

ALTER TABLE QUARTO ADD CONSTRAINT check_ocupado_s_n CHECK(OCUPADO_S_N IN ('S', 'N'));

ALTER TABLE HOTEL ADD CONSTRAINT fk_id_quarto_hotel FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO(ID_QUARTO)
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE RESERVA ADD CONSTRAINT fk_id_quarto_reserva FOREIGN KEY (ID_QUARTO) REFERENCES QUARTO(ID_QUARTO);

-- CREATE SEQUENCE SQ_ID_QUARTO
-- 	 START WITH     1
-- 	 INCREMENT BY   1
-- 	 NOCACHE
-- 	 NOCYCLE;
DROP TABLE IF EXISTS SERVICO;

CREATE TABLE SERVICO (
	ID_SERVICO	    INT(10) AUTO_INCREMENT PRIMARY KEY,
	NOME_SERVICO	VARCHAR(255) NOT NULL,
	PRECO		    DECIMAL(10, 2) NOT NULL,
	DISPONIVEL_S_N	CHAR(1)
);


ALTER TABLE SERVICO ADD CONSTRAINT check_disponivel_s_n CHECK(DISPONIVEL_S_N IN ('S', 'N'));

-- CREATE SEQUENCE SQ_ID_SERVICO
-- 	 START WITH     1
-- 	 INCREMENT BY   1
-- 	 NOCACHE
-- 	 NOCYCLE;

DROP TABLE IF EXISTS TB_REF_DOMINIO;

CREATE TABLE TB_REF_DOMINIO (
	REF_DOMINIO	VARCHAR(255) NOT NULL,
	REF_VALOR	VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS TB_COBRANCA_HOTEL;

CREATE TABLE TB_COBRANCA_HOTEL(
	ID_HOTEL	     INT(10),
    MAL_AVALIADO     CHAR(1) NOT NULL DEFAULT 'N',
    VALOR_DESCONTO   DECIMAL(10, 2)
);

ALTER TABLE TB_COBRANCA_HOTEL ADD CONSTRAINT fk_id_hotel_prec FOREIGN KEY (ID_HOTEL)
    REFERENCES HOTEL (ID_HOTEL);

ALTER TABLE TB_COBRANCA_HOTEL ADD CONSTRAINT crs_check_mal_av_s_n CHECK(MAL_AVALIADO IN ('S', 'N'));

ALTER TABLE TB_COBRANCA_HOTEL ADD CONSTRAINT crs_check_val_desc CHECK(VALOR_DESCONTO <= 100
    AND VALOR_DESCONTO >= 0 OR VALOR_DESCONTO IS NULL);

DROP TABLE IF EXISTS TB_COBRANCA_USUARIO;

CREATE TABLE TB_COBRANCA_USUARIO(
	ID_USUARIO	   INT(10),
    VALOR_DESCONTO DECIMAL(10, 2)
);

ALTER TABLE TB_COBRANCA_USUARIO ADD CONSTRAINT fk_id_user_prec FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE TB_COBRANCA_USUARIO ADD CONSTRAINT crs_check_val_desc_user CHECK(VALOR_DESCONTO <= 100
    AND VALOR_DESCONTO >= 0);
